### ISSUE TITLE
Link in repo description is wrong.

### ISSUE THREAD

**Issue by TheTommyTwitch** [DerFlatulator/haloapi.js#2]
https://derflatulator.github.io/haloapi/docco/haloapi.html 
should be changed to 
https://derflatulator.github.io/haloapi.js/docco/haloapi.html

**Comment by DerFlatulator** [comment]
Thanks, fixed. 
As you may have guessed this is a result of renaming the repository. With GitHub, old links to repositories work, but not on GitHub Pages, apparently.
