### ISSUE TITLE
[Documentation] Options parameter should be "modes" instead of "mode" for the Player Matches endpoint

### ISSUE THREAD

**Issue by stv8** [DerFlatulator/haloapi.js#4]
The parameter should be `modes` instead of `mode` as stated in the docs. 

https://developer.haloapi.com/docs/services/560af163e2f7f710cc79e517/operations/560af163e2f7f703f8349976

![haloapidocerror](https://cloud.githubusercontent.com/assets/5158539/13090559/23b35c9a-d4bc-11e5-934d-f00008437c50.png)

**Comment by DerFlatulator** [comment]
Sorry for the delay in closing this.
