### ISSUE TITLE
Update to the Events API

### ISSUE THREAD

**Issue by dougiefresh49** [DerFlatulator/haloapi.js#7]
Looks like 343 is updating 2 id's on the events API according to their [blog post](https://www.halowaypoint.com/en-us/forums/01b3ca58f06c4bd4ad074d8794d2cf86/topics/update-to-the-events-api/61bc1be2-1bdf-4830-8d8e-7ebcade87c99/posts) today

The changes to the api are as follows
- [KillerAttachmentIds](https://github.com/DerFlatulator/haloapi.js/blob/master/ts/stats/MatchEvents.d.ts#L72) is now KillerWeaponAttachmentIds
- [KillerStockId](https://github.com/DerFlatulator/haloapi.js/blob/master/ts/stats/MatchEvents.d.ts#L75) is now KillerWeaponStockId

**Comment by DerFlatulator** [comment]
Fixed in #8
